{% set version = "0.2.9.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-broom.mixed
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/broom.mixed_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/broom.mixed/broom.mixed_{{ version }}.tar.gz
  sha256: 7631cd29316a32050b9e72057754e053d7f9064a75900bb7e69b29ebca6c60b2

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-broom
    - r-coda
    - r-dplyr
    - r-forcats
    - r-furrr
    - r-nlme
    - r-purrr
    - r-stringr
    - r-tibble
    - r-tidyr
  run:
    - r-base
    - r-broom
    - r-coda
    - r-dplyr
    - r-forcats
    - r-furrr
    - r-nlme
    - r-purrr
    - r-stringr
    - r-tibble
    - r-tidyr

test:
  commands:
    - $R -e "library('broom.mixed')"           # [not win]
    - "\"%R%\" -e \"library('broom.mixed')\""  # [win]

about:
  home: http://github.com/bbolker/broom.mixed
  license: GPL-3.0-only
  summary: "Convert fitted objects from various R mixed-model packages into tidy data frames along the lines of the 'broom' package. The package provides three S3 generics for each model: tidy(), which summarizes a model's statistical findings such as coefficients of a regression; augment(), which adds columns to the original\
    \ data such as predictions, residuals and cluster assignments; and glance(), which provides a one-row summary of model-level statistics."
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: broom.mixed
# Type: Package
# Title: Tidying Methods for Mixed Models
# Version: 0.2.4
# Authors@R: c( person("Ben", "Bolker", email = "bolker@mcmaster.ca", role = c("aut", "cre"), comment=c(ORCID="0000-0002-2127-0443")), person("David", "Robinson", email = "admiral.david@gmail.com", role = "aut"), person("Dieter", "Menne", role = "ctb"), person("Jonah", "Gabry", role = "ctb"), person("Paul", "Buerkner", role = "ctb"), person("Christopher", "Hua", role = "ctb"), person("William", "Petry", role = "ctb", comment=c(ORCID="0000-0002-5230-5987")), person("Joshua", "Wiley", role = "ctb", comment=c(ORCID="0000-0002-0271-6702")), person("Patrick", "Kennedy", role = "ctb") )
# Maintainer: Ben Bolker <bolker@mcmaster.ca>
# Description: Convert fitted objects from various R mixed-model packages into tidy data frames along the lines of the 'broom' package. The package provides three S3 generics for each model: tidy(), which summarizes a model's statistical findings such as coefficients of a regression; augment(), which adds columns to the original data such as predictions, residuals and cluster assignments; and glance(), which provides a one-row summary of model-level statistics.
# Imports: broom, dplyr, tidyr, plyr, purrr, tibble, reshape2, nlme, methods, stringr, coda, TMB
# Suggests: knitr, testthat, ggplot2, Matrix, MCMCglmm, lme4, rstan, rstanarm, brms, mgcv, gamlss, gamlss.data, lmerTest, glmmADMB, glmmTMB, dotwhisker, pander, R2jags
# URL: http://github.com/bbolker/broom.mixed
# BugReports: http://github.com/bbolker/broom.mixed/issues
# License: GPL-3
# RoxygenNote: 6.1.1
# Encoding: UTF-8
# Additional_repositories: http://bbolker.github.io/drat
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-02-21 17:03:53 UTC; bolker
# Author: Ben Bolker [aut, cre] (<https://orcid.org/0000-0002-2127-0443>), David Robinson [aut], Dieter Menne [ctb], Jonah Gabry [ctb], Paul Buerkner [ctb], Christopher Hua [ctb], William Petry [ctb] (<https://orcid.org/0000-0002-5230-5987>), Joshua Wiley [ctb] (<https://orcid.org/0000-0002-0271-6702>), Patrick Kennedy [ctb]
# Repository: CRAN
# Date/Publication: 2019-02-21 23:50:03 UTC
