appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: HNQ3s0hH4fO8MipuKuvhdQr/MuppwRTB2evbSdLDegfhmRHZ3lz9yoa49I+lSCECbPi/PEkdTSqRAm+OKLOYdL7/BtXmQzTkxMQnSyCnfSeEHaVhpZxWxURKlxOCfPuLARqRygWMWoP6g1JDwWFOg8Z5hMu3r42GdIiKzAvvsx47lFbfkwRJSyFw5FicT36f15SmKxnVfgpyfdv2qsVNHcza4vFRGRxVxQo6TvR22L+yJHeMN7RsyA27BbCY9BGzAelpngyID10ZUij37gIz1IZ8GsXCZu/FlXriVH0X+nf+p5g9C+QZT3jRqI3acHSDZk9yZHTbLG53piqwpYaR4JtMc4oYJfyqAhhDrJIUdNpX5/HIVGEXyfV/TtyrXiW133IHVoHkC4WjOowar6bl7h4hBubGWOARo41P1lwMdhMKdH/6O2xtW4wJ906KHlUzMOKJaN7BgFJgL1imojsZDh/wbaKcEjG7fHVA5NE5kD1YEoPztubV82eq3MJWgGvCHe413sGfavvxXyfiV7/VpgWq1H+w0ArPags1hQ1Y0I5UcM1oBXtIVeDD+tBOXK/J6a4o48fGFyJ8V1lz6EtrUEAGsssgSAVBMXS2jhHah/IFNNRVvos+dPDA/O3mqnJej0ncGPyk1jHTHr6nvXzKMK6V8KfH33QQfCf+OTvx/C4=}
